
create SEQUENCE Update_sequence
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;


var b_por_aum1 nvarchar2(50)
var b_por_aum2 nvarchar2(50)
var b_por_aum3 nvarchar2(50)
exec :b_por_aum1 := 'Servicio de Atención Primaria de Urgencia (SAPU)';  
exec :b_por_aum2 := 'Hospitales del área de la Salud Pública' ;
exec :b_por_aum3 := 'Centros de Salud Familiar (CESFAM)';

set SERVEROUTPUT ON
DECLARE
CURSOR cur_datos_med IS
    select m.med_run rut, u.uni_id id_unidad, m.pnombre||' '||m.snombre||' '||m.apaterno nombre, count(a.med_run) nro_atenciones,
    u.nombre nombre_unida
    from medico m 
    inner join unidad u on u.uni_id = m.uni_id
    left outer join atencion a on a.med_run = m.med_run --and m.med_run is not null
                and to_char(nvl(a.fecha_atencion,'01/01/2021'), 'yyyy') = '2021'     --- SE REEMPLAZA WHERE POR AND       
                group by m.med_run, m.pnombre||' '||m.snombre||' '||m.apaterno,u.uni_id,u.nombre
                having count(a.med_run) < (select max(count(*)) from atencion 
                                            where to_char(fecha_atencion,'yyyy')=2021
                                            group by med_run)
            order by m.med_run;
      
-- DCLARO EL ARRAY PARA ALMACENAR LOS VALORES DE MULTA POR ESPECIALIDAD      
TYPE tp_varray_destinacion IS VARRAY(3) 
         OF NVARCHAR2(50);
v_array_destination  tp_varray_destinacion;

v_destinacion nvarchar2(50) ;
BEGIN
EXECUTE IMMEDIATE ('TRUNCATE TABLE medico_servicio_comunidad');

  v_array_destination:= tp_varray_destinacion(:b_por_aum1,:b_por_aum2,:b_por_aum3);
   
for item in cur_datos_med LOOP 
      
    v_destinacion:= 
    CASE 
        WHEN (item.id_unidad = 100 OR item.id_unidad = 400) and item.nro_atenciones >= 0 THEN
        v_array_destination(1)
        WHEN item.id_unidad = 200  and item.nro_atenciones BETWEEN 0 and 3 THEN
        v_array_destination(1)
        WHEN  item.id_unidad = 200  and item.nro_atenciones > 3 THEN
        v_array_destination(2)
        WHEN (item.id_unidad = 500 OR item.id_unidad = 900) and item.nro_atenciones >=0 THEN
        v_array_destination(2)
        WHEN(item.id_unidad = 700 OR item.id_unidad = 800) and item.nro_atenciones  BETWEEN 0 and 3 THEN
        v_array_destination(1)
        WHEN (item.id_unidad = 700 OR item.id_unidad = 800) and item.nro_atenciones  > 3 THEN
        v_array_destination(2)
        WHEN item.id_unidad = 300  and item.nro_atenciones  >= 0 THEN
        v_array_destination(2)
        WHEN item.id_unidad = 600  and item.nro_atenciones  >= 0 THEN
        v_array_destination(3)
        WHEN item.id_unidad = 1000  and item.nro_atenciones   > 3 THEN
        v_array_destination(2)
        WHEN item.id_unidad = 1000  and item.nro_atenciones    BETWEEN 0 and 3 THEN
        v_array_destination(1)
        end;
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('item.nombre '|| item.nombre);
        DBMS_OUTPUT.PUT_LINE('item '||item.nombre_unida);
        DBMS_OUTPUT.PUT_LINE('v_destinacion '|| v_destinacion);
        DBMS_OUTPUT.PUT_LINE(' nro_atenciones '|| item.nro_atenciones);
        DBMS_OUTPUT.PUT_LINE('================================');
       
        
        
        insert into medico_servicio_comunidad values ( item.nombre_unida, item.rut, item.nombre,
                                                        'correo@correo.cl',item.nro_atenciones, v_destinacion);
        
 END LOOP;

END; 

ALTER TABLE medico_servicio_comunidad MODIFY id_med_scomun GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE medico_servicio_comunidad MODIFY (ID NUMBER GENERATED BY DEFAULT AS IDENTITY); 

--select * from medico_servicio_comunidad;